#生产环境
#服务启动端口
server:
  port: 8003
#服务名称（服务注册到eureka的名称）
spring:
  application:
    name: app-huaita-member
#服务注册eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

    register-with-eureka: true
    fetch-registry: true
