#生产环境
#服务启动端口
server:
  port: 8002
#服务名称（服务注册到eureka的名称）
spring:
  application:
    name: app-huaita-order
  cloud:
    client:
      ipAddress: 127.0.0.1

#服务注册eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

    register-with-erueka: true
    fetch-registry: true